global:
  email:
    from: gitlab@local.test
    reply_to: gitlab@local.test
  smtp:
    enabled: false
  appConfig:
    object_store:
      enabled: true
      proxy_download: true
      connection:
        secret: gitlab-object-storage
        key: config
    artifacts:
      enabled: false
    lfs:
      enabled: true
      bucket: git-lfs
    uploads:
      enabled: false
    packages:
      enabled: false
  edition: ce
  registry:
    enabled: false
  shell:
    port: 2222
  hosts:
    domain: localhost
    https: false
  kas:
    enabled: false
  psql:
    database: gitlab
    host: gitlab-postgres-rw.gitlab.svc.cluster.local
    version: 17
    password:
      key: password
      secret: pgsql-secrets
    username: postgres
  redis:
    host: valkey.gitlab.svc.cluster.local
    port: 6379
    auth:
      enabled: false
  gatewayApi:
    enabled: false
    installEnvoy: false
    configureCertmanager: false
    httpToHttpsRedirect: false
  ingress:
    enabled: true
    class: traefik
    configureCertmanager: false
    tls:
      enabled: false

nginx-ingress:
  enabled: false

installCertmanager: false

certmanager-issuer:
  email: gitlab@local.test

registry:
  enabled: false

redis:
  install: false

prometheus:
  install: false

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    workerProcesses: 1
    puma:
      threads:
        min: 2
        max: 2
      disableWorkerKiller: false
      workerMaxMemory: 900
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 2
        memory: 3Gi
    workhorse:
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 500m
          memory: 256Mi
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    concurrency: 5
    memoryKiller:
      maxRss: 800000
      hardLimitRss: 1000000
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1200Mi
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    service:
      type: NodePort
      nodePort: 30222
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 250m
        memory: 128Mi
  gitaly:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 1Gi
    persistence:
      size: 1Gi
      storageClass: local-path
  gitlab-exporter:
    enabled: false
  toolbox:
    enabled: false
    backups:
      cron:
        enabled: false
gitlab-runner:
  install: false
