# -*- mode: ruby -*-
# vi: set ft=ruby :

LOGIN = "sidiallo"

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian12"

  config.vm.define "#{LOGIN}S" do |server|
    server.vm.hostname = "#{LOGIN}S"
    server.vm.network "private_network",
      ip: "192.168.56.110",
      libvirt__network_name: "iot_network",
      libvirt__dhcp_enabled: false

    server.vm.provider :libvirt do |lv|
      lv.memory = 1024
      lv.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "#{LOGIN}SW" do |worker|
    worker.vm.hostname = "#{LOGIN}SW"
    worker.vm.network "private_network",
      ip: "192.168.56.111",
      libvirt__network_name: "iot_network",
      libvirt__dhcp_enabled: false

    worker.vm.provider :libvirt do |lv|
      lv.memory = 1024
      lv.cpus = 1
    end

    worker.vm.provision "shell", path: "scripts/serverworker.sh"
  end

  config.vm.define "#{LOGIN}test" do |test|
    test.vm.hostname = "#{LOGIN}test"
    test.vm.network "private_network",
      ip: "192.168.56.112",
      libvirt__network_name: "iot_network",
      libvirt__dhcp_enabled: false

    test.vm.provider :KVM do |bla|
      bla.memory = 1024
      bla.cpus = 1
    end
  end


end